# Generated by Django 5.1.6 on 2025-03-01 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trvels', '0008_location_backimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('sequence', models.IntegerField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_locations', to='Trvels.location')),
            ],
            options={
                'ordering': ['location', 'sequence'],
            },
        ),
    ]
